apiVersion: v1
kind: Service
metadata:
  name: jaya-aws-service
  labels:
    apps: jaya-awsapp
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: jaya-aws-service
  selector:
    name: jaya-aws
    app: jaya-awsapp