apiVersion: v1
kind: Service
metadata:
  name: jaya-nginx-service
  labels:
    apps: jaya-web
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: vote-service
  selector:
    name: jaya-nginx
    app: jaya-web